prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdfa: <http://www.w3.org/ns/rdfa#>
prefix schema: <http://schema.org/>

construct {

    [] a rdfa:Warning; rdfs:label ?label; rdfa:context ?term

} where {

    {
        graph ?doc { ?thing ?term ?value }
        filter not exists { ?term a rdf:Property }
        bind("Unknown property"@en as ?label)
    } union {
        graph ?doc { ?thing a ?term }
        filter not exists { ?term a rdfs:Class }
        bind("Unknown class"@en as ?label)
    }
    filter(strStarts(str(?term), str(schema:)))

}
